### ISSUE TITLE
dtsm install generates invalid reference path

### ISSUE THREAD

**Issue by virifi** [vvakame/dtsm#10]
From version 0.10.0, `dtsm install` generates bundle.d.ts in which reference paths point to invalid path.

Run `dtsm install` in the directory in which following `dtsm.json` exists,
```
{
  "repos": [
    {
      "url": "https://github.com/borisyankov/DefinitelyTyped.git",
      "ref": "master"
    }
  ],
  "path": "typings",
  "bundle": "typings/bundle.d.ts",
  "link": {
    "npm": {
      "include": true
    }
  },
  "dependencies": {
    "node/node.d.ts": {
      "ref": "75903dbb9edbd1af3b2d12db56df4becab543879"
    }
  }
}
```
following `typings/bundle.d.ts` is generated but the file  `../../node/node.d.ts` does not exist.
```
/// <reference path="../../node/node.d.ts" />
```

Run `dtsm install` with version 0.9.2, `typings/bundle.d.ts` is generated as shown below.
```
/// <reference path="node/node.d.ts" />
```

### Environment
- Mac OSX Yosemite 10.10.3
- Node.js v0.12.2

**Comment by vvakame** [comment]
@virifi @mizchi thank you for your report! dtsm 0.10.2 released. please try it.

**Comment by virifi** [comment]
Nice work! Thanks.
