### ISSUE TITLE
dtsm version 0.10.2 generates invalid reference path on Windows

### ISSUE THREAD

**Issue by virifi** [vvakame/dtsm#12]
With dtsm version 0.10.2, `dtsm install` generates invalid reference path only on Windows.

```sh
$ npm install -g dtsm@0.10.2
$ dtsm init
$ dtsm install node --save
```

The resulting `typings\bundle.d.ts` is

```
/// <reference path="typings\node\node.d.ts" />
```

With version 0.9.2

```sh
$ npm install -g dtsm@0.9.2
$ dtsm init
$ dtsm install node --save
```

The resulting `typings\bundle.d.ts` is

```
/// <reference path="node\node.d.ts" />
```

### Environment
- Windows 8.1 Pro
- Node v0.12.2

On Mac OSX Yosemite 10.10.3, `bundle install` works properly.

**Comment by vvakame** [comment]
@virifi thank you for your reporing! and thanks @rei000! I just release dtsm 0.10.3. please try it.
