### ISSUE TITLE
-i (interactive) does not work on windows

### ISSUE THREAD

**Issue by basarat** [vvakame/dtsm#15]
![image](https://cloud.githubusercontent.com/assets/874898/8100474/4b164c84-104f-11e5-98f4-fbe9bbf0bb47.png)

Perhaps its not supported?

**Comment by Semigradsky** [comment]
From README:
> If you use peco, you can install .d.ts file interactive.

You installed [peco](https://github.com/peco/peco)?

**Comment by basarat** [comment]
Indeed it works. I got the ref from this comment https://github.com/vvakame/dtsm/issues/14#issuecomment-111000000 and didn't read the readme :+1:
