### ISSUE TITLE
Can't use in proxy

### ISSUE THREAD

**Issue by 82p** [vvakame/dtsm#20]
How can I use dtsm in proxy?
I can not find settings. 

dtsmをプロキシ下で動かす方法はありますか？

**Comment by vvakame** [comment]
sorry I never try to do that.
dtsm use git command. I think if you use git command in proxy, You can use it.
BTW, dtsm is deprecated now. you should use [@types](https://www.npmjs.com/~types).

試した事はないですね。
dtsmはgitコマンドを内部で使っているので、gitコマンドがproxy環境下で動けば動くと思います。
ところで、dtsmは現在非推奨になったので[@types](https://www.npmjs.com/~types)の利用をおすすめします。

**Comment by 82p** [comment]
thx I try it.

ありがとうございます。@typesを試してみます。
