### ISSUE TITLE
'dtsm search' raises an error on Windows 10

### ISSUE THREAD

**Issue by tyru** [vvakame/dtsm#22]
I installed `dtsm` and ran `dtsm init` and `dtsm search angular`, after long run (about a minute), it raised the following stacktrace.
I ran on Windows 10 and cmd.exe .
If once `dtsm search angular` is executed, the next run is very fast response but the result is same.

```
C:\Users\tyru>dtsm search angular
fetching https://github.com/DefinitelyTyped/DefinitelyTyped.git
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:266:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

**Comment by tyru** [comment]
sorry... I'm newbie and I didn't notice `typings` command replaced this tool.
please ignore or close this.

**Comment by vvakame** [comment]
@tyru thank you for reporting! now, you should use [@types](https://www.npmjs.com/~types) packages. It supported by compiler native.

**Comment by tyru** [comment]
Thanks for info!
I was struggling but finally get to it.

[TypeScript 入門 + Express 再入門した](http://tyru.hatenablog.com/entry/2017/02/19/212009)
