### ISSUE TITLE
Install failed: npm ERR! version not found: packagemanager-backend@0.3.3

### ISSUE THREAD

**Issue by mizchi** [vvakame/dtsm#4]
$ npm install -g dtsm
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/mizchi/.nodebrew/current/bin/npm" "install" "-g" "dtsm"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12

npm ERR! version not found: packagemanager-backend@0.3.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mizchi/proj/kobito-shell/application/npm-debug.log

**Comment by vvakame** [comment]
@mizchi oops, sorry!
dtsm 0.6.2 was released.
please try again.

**Comment by mizchi** [comment]
ty
