### ISSUE TITLE
dtsm のDT外リポジトリの構成について

### ISSUE THREAD

**Issue by gyohk** [vvakame/dtsm#7]
例えば、DT 内にある A という定義ファイルと、 
DT外の B という定義ファイル両方をプロジェクトで同時に使いたいという場合、
A・B 共に jquery.d.ts を参照していると、
dtsm を実行したタイミングでそれぞれ別の場所に読み込まれてしまい、
Duplicate identifier のエラーが出てしまいます。
とりあえずはB のリポジトリ構成を工夫して、
jquery.d.ts がABどちらからも同じパスに読み込まれるようにすれば良いのですが、
リポジトリルートのbower.json 的な仕組みがあったほうが良い気がしました。

**Comment by vvakame** [comment]
@gyohk いちおー、自分のdtsm.json内部でDT外の定義ファイルのコピー先の制御があります。
https://github.com/vvakame/dtsm/blob/master/example/otherRepo/dtsm.json この辺。
パス変更の制御を自動でできるように、dtsm-serve.json みたいなものはほしいなーと思ってました。
できれば、使っているDT外のリポジトリを見させてほしいとです。

**Comment by gyohk** [comment]
pathオプション見落としてました...。
実際には依存ライブラリが jquery ではなく createjs なのですが、リポジトリはこちらになります。
https://github.com/gyohk/TSDef_BitmapDataForCreateJS

今のところ、定義ファイルがtypings ではなく、ルート階層にフラットに展開されるようにしてます。

**Comment by vvakame** [comment]
なるほど。

```
$ dtsm init
$ dtsm install easeljs --save
$ dtsm --remote git@github.com:gyohk/TSDef_BitmapDataForCreateJS.git install bitmapdata-for-createjs --save
$ cat dtsm.json
{
  "repos": [
    {
      "url": "https://github.com/borisyankov/DefinitelyTyped.git",
      "ref": "master"
    }
  ],
  "path": "typings",
  "bundle": "typings/bundle.d.ts",
  "dependencies": {
    "easeljs/easeljs.d.ts": {
      "ref": "e57df787f4e11601625d7e1c1b2ee351b97a18a1"
    },
    "bitmapdata-for-createjs/bitmapdata-for-createjs.d.ts": {
      "repo": "git@github.com:gyohk/TSDef_BitmapDataForCreateJS.git",
      "ref": "a2d99cf6f0de4dfc7520fd9d7ef8b63d7ea8b00f"
    }
  }
}
$ find typings
typings
typings/bitmapdata-for-createjs
typings/bitmapdata-for-createjs/bitmapdata-for-createjs.d.ts
typings/bundle.d.ts
typings/createjs-lib
typings/createjs-lib/createjs-lib.d.ts
typings/easeljs
typings/easeljs/easeljs.d.ts
typings/tweenjs
typings/tweenjs/tweenjs.d.ts
```

こんな感じで、うまくいきそうな気がしますね…。

**Comment by gyohk** [comment]
実際には、こちらのリポジトリで参照しています。
https://github.com/gyohk/createjs-typescript-template/

現在は、利用側(というか自分ですが)が特に何もせず動くように、少しリポジトリ内のレイアウトを変えてます。
ただ、DTの定義ファイルがリポジトリルートにフラットに展開されてしまうので、
数が多いときに.gitignore 書くのがちょっと大変だなと。

**Comment by vvakame** [comment]
https://twitter.com/gyoh_k/status/589782770672541696 とのこと。
一応解決、とします。
