### ISSUE TITLE
Link feature

### ISSUE THREAD

**Issue by Semigradsky** [vvakame/dtsm#9]
Discovery and linking of definitions from packages installed with node or bower - https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions
Very cool feature

**Comment by vvakame** [comment]
@Semigradsky it released! please try dtsm@0.10.1

**Comment by Semigradsky** [comment]
@vvakame
I am trying link packages and this happened only after I install dependencies (`npm i`).
Are you just copy the links to all files *.d.ts? Are you sure it's a good idea?

**Comment by vvakame** [comment]
@Semigradsky what behavior do you expect?

**Comment by Semigradsky** [comment]
@vvakame sorry. I'm very confused) Everything is fine. :+1:

**Comment by vvakame** [comment]
:+1:
